#!/bin/bash
#PBS -N mgzn2_phonons_2
#PBS -q v1_small72
#PBS -l select=1:ncpus=1:mem=2gb
#PBS -l walltime=00:15:00
#PBS -j oe
#PBS -V

cd $PBS_O_WORKDIR

module load LAMMPS/2Aug2023_update2-foss-2023a-kokkos

LAMMPS_CMD=lmp

for i in $(seq -w 001 005); do
    echo "Running displacement $i ..."
    sed "s/supercell-001/supercell-$i/" mgzn2_phonons_2_in.force > temp_$i.in

    $LAMMPS_CMD -in temp_$i.in

    mv forces.dump forces-$i.dump
done

